### ISSUE TITLE
Lets color it up

### ISSUE THREAD

**Issue by pratik60** [kbsjunk/fuzzy-typeahead#2]
Rather than highlighting it in bold, coloring it would make it look more attractive and better. Thoughs?

**Comment by kitbs** [comment]
Hi Pratik

I am not maintaining this any more, but you can feel free to use it however you like. You might like to use some CSS to change the colour, like so:

.typeahead.dropdown-menu>li>a>b {
  color: green;
}

I would not recommend that you use this in your real applications, because it was just an experiment of mine and not thoroughly tested.

Have fun!
